.github/workflows/ci.yml

ci(repo): change package manager to pnpm in gh workflow

---

.prettierignore
.vscode/settings.json
apps/cms/src/payload.config.ts
apps/web-e2e/eslint.config.js
apps/web-e2e/playwright.config.ts
apps/web-e2e/src/example.spec.ts
apps/web/eslint.config.js
apps/web/src/app/app.spec.tsx
apps/web/src/app/app.tsx
apps/web/tailwind.config.js
apps/web/vite.config.ts
eslint.config.js
pnpm-lock.yaml

style(repo): add imports eslint rule and enable auto format

---

apps/cms/.env.local
apps/cms/Dockerfile
apps/cms/Dockerfile.dockerignore
apps/cms/docker-compose.yml
apps/cms/project.json

refactor(cms): use npm as package manager in dockerfile

---

apps/cms/Dockerfile

fix(cms): remove package lock file from gitignore during docker build

---

apps/cms/src/collections/Users.ts
apps/cms/src/payload.config.ts

feat(cms): add localization to payload config

---

.vscode/launch.json
apps/cms/project.json

chore(cms): enable debugging of cms app

---

apps/cms/.env.local
apps/cms/src/env.ts
apps/cms/src/main.ts
apps/cms/src/payload.config.ts
apps/cms/tsconfig.app.json

feat(cms): make process env type-safe

---

lefthook.yml

fix(repo): use pnpm for linting commit message

---

.github/workflows/nx-migrate.yml
README.md
packages/nx-migrate-action/README.md

ci(repo): use codeware bot token in nx migrate workflow

---

packages/nx-migrate-action/src/lib/utils/parse-name-email.ts

perf(nx-migrate-action): improve performance of name email regex

---

apps/cms/src/collections/Users.ts
apps/cms/src/generated/payload-types.ts
apps/cms/src/generated/schema.graphql
apps/cms/src/migrations/20241115_142550.json
apps/cms/src/migrations/20241115_142550.ts
apps/cms/src/payload.config.ts

feat(cms): enable api key authenticaion on users collection

---

e2e/utils/ensure-create-nx-workspace-project.ts

chore(e2e-utils): add eslint workaround due to a blocker in 9.15

---

.github/workflows/publish-package.yml

ci(repo): add workflow to publish package from tag events

---

packages/create-nx-payload/package.json

chore(create-nx-payload): bump version since 1.0.0 is a broken publish

---

.github/workflows/nx-migrate.yml

ci(repo): use codeware actions bot as nx migrate committer

---

apps/cms/src/collections/Pages.ts
apps/cms/src/generated/payload-types.ts
apps/cms/src/hooks/format-slug.ts
apps/cms/src/hooks/populate-published-at.ts
apps/cms/src/payload.config.ts
pnpm-lock.yaml

feat(cms): add pages collection

---

packages/nx-payload/src/generators/init/__snapshots__/init.spec.ts.snap
packages/nx-payload/src/generators/init/init.spec.ts

fix(nx-payload): snapshot tests should match for version patterns

---

packages/core/package.json
packages/core/src/lib/release/release.ts
packages/core/src/lib/release/revert-package-json.ts

fix(core): add workaround for nx release changing workspace package.json

---

.github/workflows/publish-package.yml

fix(repo): publish package tags pattern

---

apps/cms/src/collections/Articles.ts
apps/cms/src/generated/payload-types.ts
apps/cms/src/migrations/20241203_122433.json
apps/cms/src/migrations/20241203_122433.ts
apps/cms/src/payload.config.ts
libs/shared/util/payload/src/lib/generated/payload-types.ts
package.json
pnpm-lock.yaml

feat(cms): create article collection

---

packages/nx-fly-deployment-action/src/lib/fly-deployment.spec.ts
packages/nx-fly-deployment-action/src/lib/utils/run-destroy-apps.ts

fix(nx-fly-deployment-action): deprecated apps filter returned too much

---

.github/workflows/publish-package.yml
commitlint.config.js

ci(workflow): fix publish-package tag pattern

---

packages/core/src/lib/release/publish.ts

fix(core): detect package manager before publish release

---

.github/renovate.json
package.json
pnpm-lock.yaml

ci(workflow): renovate should ignore eslint-config-prettier

---

apps/cms/src/components/Logo/index.tsx
apps/cms/src/payload.config.ts
apps/cms/tsconfig.app.json
apps/web/app/root.tsx
apps/web/middlewares/resolve-dev-api-key.ts
apps/web/package.json
apps/web/project.json
apps/web/tailwind.config.cjs
libs/shared/ui/react-components/.babelrc
libs/shared/ui/react-components/eslint.config.js
libs/shared/ui/react-components/project.json
libs/shared/ui/react-components/src/index.ts
libs/shared/ui/react-components/src/lib/cdwr-cloud.tsx
libs/shared/ui/react-components/tsconfig.json
libs/shared/ui/react-components/tsconfig.lib.json
libs/shared/ui/react-components/tsconfig.spec.json
libs/shared/ui/react-components/vite.config.ts
nx.json
package.json
pnpm-lock.yaml
tsconfig.base.json

feat(cms): use codeware logo on admin login page

---

.github/workflows/fly-deployment.yml
packages/fly-node/README.md
packages/fly-node/src/lib/fly.class.spec.ts
packages/fly-node/src/lib/fly.class.ts
packages/fly-node/src/lib/types.ts
packages/nx-fly-deployment-action/action.yml
packages/nx-fly-deployment-action/src/lib/__snapshots__/schemas.spec.ts.snap
packages/nx-fly-deployment-action/src/lib/fly-deployment.spec.ts
packages/nx-fly-deployment-action/src/lib/main.spec.ts
packages/nx-fly-deployment-action/src/lib/main.ts
packages/nx-fly-deployment-action/src/lib/schemas/__fixtures__/action-inputs.json
packages/nx-fly-deployment-action/src/lib/schemas/__fixtures__/deployment-config.json
packages/nx-fly-deployment-action/src/lib/schemas/action-inputs.schema.ts
packages/nx-fly-deployment-action/src/lib/schemas/deployment-config.schema.ts
packages/nx-fly-deployment-action/src/lib/utils/get-deployment-config.ts
packages/nx-fly-deployment-action/src/lib/utils/run-deploy-apps.ts

Opt out fly depot builder on deploy

---

apps/cms/Dockerfile
package.json
pnpm-lock.yaml

fix(cms): remove peer libs docker workaround
